# Rustfmt configuration
edition = "2024"

# Line width
max_width = 100
comment_width = 80

# Indentation
tab_spaces = 4
hard_tabs = false

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Formatting style
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
fn_single_line = false
where_single_line = false
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = true

# Comments
normalize_comments = false
wrap_comments = false
format_code_in_doc_comments = true

# Other
use_field_init_shorthand = true
use_try_shorthand = true
force_multiline_blocks = false
